# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bowlers',
            fields=[
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('wkts', models.FloatField(blank=True, db_column='Wkts', null=True)),
                ('ave', models.FloatField(blank=True, db_column='Ave', null=True)),
                ('econ', models.FloatField(blank=True, db_column='Econ', null=True)),
                ('sr', models.FloatField(blank=True, db_column='SR', null=True)),
                ('totalovers', models.FloatField(blank=True, null=True)),
                ('matches', models.FloatField(blank=True, db_column='Matches', null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('Playing_Role', models.TextField(choices=[('Playing role Bowler', 'Playing role Bowler'), ('Playing role Allrounder', 'Playing role Allrounder'), ('Playing role Bowling allrounder', 'Playing role Bowling allrounder'), ('Playing role Batting allrounder', 'Playing role Batting allrounder')], default='Select from')),
                ('bat', models.TextField(blank=True, null=True)),
                ('bowl', models.TextField(blank=True, null=True)),
                ('ahp_closeness_ratio', models.FloatField(blank=True, db_column='ahp_closeness_ratio', null=True)),
                ('ahprank', models.FloatField(blank=True, db_column='ahprank', null=True)),
                ('pcarank', models.FloatField(blank=True, db_column='pcarank', null=True)),
            ],
            options={
                'db_table': 'bowlers',
            },
        ),
    ]
