# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batsmen',
            fields=[
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('inningsplayed', models.FloatField(blank=True, db_column='InningsPlayed', null=True)),
                ('runs', models.FloatField(blank=True, db_column='Runs', null=True)),
                ('ave', models.FloatField(blank=True, db_column='Ave', null=True)),
                ('sr', models.FloatField(blank=True, db_column='SR', null=True)),
                ('dotball', models.FloatField(blank=True, null=True)),
                ('hardhitter', models.FloatField(blank=True, db_column='HardHitter', null=True)),
                ('finisher', models.FloatField(blank=True, db_column='Finisher', null=True)),
                ('hf', models.FloatField(blank=True, db_column='HF', null=True)),
                ('fifty', models.FloatField(blank=True, db_column='Fifty', null=True)),
                ('zeros', models.FloatField(blank=True, db_column='Zeros', null=True)),
                ('centuries', models.FloatField(blank=True, db_column='Centuries', null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('role', models.TextField(blank=True, choices=[('Playing role Bowler', 'Playing role Bowler'), ('Playing role Allrounder', 'Playing role Allrounder'), ('Playing role Bowling allrounder', 'Playing role Bowling allrounder'), ('Playing role Batting allrounder', 'Playing role Batting allrounder')], null=True, verbose_name='Playing Role')),
                ('bat', models.TextField(blank=True, null=True)),
                ('bowl', models.TextField(blank=True, null=True)),
                ('pca', models.FloatField(blank=True, db_column='PCA', null=True)),
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True, verbose_name='PCA Rank')),
                ('ahprank', models.FloatField(blank=True, db_column='Ahprank', null=True, verbose_name='AHP Rank')),
                ('ahpclosenessrank', models.FloatField(blank=True, db_column='Ahpclosenessrank', null=True)),
            ],
            options={
                'db_table': 'batsmen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bowlers',
            fields=[
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('wkts', models.FloatField(blank=True, db_column='Wkts', null=True)),
                ('ave', models.FloatField(blank=True, db_column='Ave', null=True)),
                ('econ', models.FloatField(blank=True, db_column='Econ', null=True)),
                ('sr', models.FloatField(blank=True, db_column='SR', null=True)),
                ('wickettaker', models.FloatField(blank=True, db_column='WicketTaker', null=True)),
                ('totalovers', models.FloatField(blank=True, null=True)),
                ('matches', models.FloatField(blank=True, db_column='Matches', null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('role', models.TextField(blank=True, choices=[('Playing role Bowler', 'Playing role Bowler'), ('Playing role Allrounder', 'Playing role Allrounder'), ('Playing role Bowling allrounder', 'Playing role Bowling allrounder'), ('Playing role Batting allrounder', 'Playing role Batting allrounder')], null=True, verbose_name='Playing Role')),
                ('bat', models.TextField(blank=True, null=True)),
                ('bowl', models.TextField(blank=True, null=True)),
                ('pca', models.FloatField(blank=True, db_column='PCA', null=True)),
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True, verbose_name='PCA Rank')),
                ('ahprank', models.FloatField(blank=True, db_column='Ahprank', null=True, verbose_name='AHP Rank')),
                ('ahpclosenessrank', models.FloatField(blank=True, db_column='Ahpclosenessrank', null=True)),
            ],
            options={
                'db_table': 'bowler',
                'managed': False,
            },
        ),
    ]
