# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_bowlers_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowlers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
