# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batsman',
            name='users',
        ),
        migrations.AlterField(
            model_name='userselect',
            name='batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batsman', to='player.Batsmen'),
        ),
        migrations.DeleteModel(
            name='Batsman',
        ),
    ]
