# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselect',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowlers', to='player.Bowlers'),
        ),
    ]
